# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1dcb3ea80158f534733022592fb02cc86c88fb2e1b2d3c619bfa84b2ee47cdc637cbd3bedb28676968d70910f98f66a8ff23afc5c3886947ea7d36e3b778d59

test:
  secret_key_base: 6ca77d10443a8030c2061b9d36b9040589782393b01787a9609e7324b149b70027298b2a33324cec16020f87ac65f49cc0c84e1caa7923f94367770199fcb0a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
